apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/axiomatics/k3s-hub-platform.git
    targetRevision: main
    path: security/wazuh/overlays/local
  
  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
