apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
spec:
  template:
    spec:
      containers:
      - name: wazuh-indexer
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        env:
          # Single-node configuration for local dev
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          - name: discovery.type
            value: "single-node"